### ISSUE TITLE
`isAdvertisingTrackingEnabled` deprecated in iOS 14.0

### ISSUE THREAD

**Issue by duartepinto** [adzerk/audience-ios-objc-sdk#31]
[iOS 14.0 will deprecate](https://developer.apple.com/documentation/adsupport/asidentifiermanager/1614148-isadvertisingtrackingenabled) the `isAdvertisingTrackingEnabled` method in favor of the [App Tracking Transparency framework](https://developer.apple.com/documentation/apptrackingtransparency).

We should update the SDK to use this framework.

**Comment by beatriz** [comment]
* Use different API based on the iOS version, with compiler flags (check `VSDKUtil.m`). 
* Change the documentation, explain which steps to go through to ask for permissions.

**Comment by thyandrecardoso** [comment]
First attempt into this done in https://github.com/velocidi/velocidi-ios-objc-sdk/pull/37

**Comment by thyandrecardoso** [comment]
Closed by velocidi-ios-objc-sdk#37
