### ISSUE TITLE
Fallback to use internal ID for tracking in iOS 14

### ISSUE THREAD

**Issue by duartepinto** [adzerk/audience-ios-objc-sdk#34]
We should be able to fallback to use the internal ID when the idfa is not available.

**Comment by thyandrecardoso** [comment]
Currently, we do not provide support to perform tracking or match requests without the idfa.

From the information given in https://developer.apple.com/app-store/user-privacy-and-data-use/ I don't think we should fallback to that when the user opts-out or does not opt-in into tracking.

In the general case, we would be matching ids to then use them for retargeting in third party platforms, which seems to go against what is described in the link above.

**Comment by duartepinto** [comment]
Those guidelines don't really address Apple's stance regarding first-party tracking. Was looking at https://digilant.com/blog/featured-blog/apple-ios-14-what-it-means-for-marketers-and-first-party-data/
and it seems to suggest that 1st party tracking falls within what is allowed. That article even mentions using the _IDFV (Identifier for Vendors)_ for it.

**Comment by duartepinto** [comment]
Also worth mentioning [OpenIDFA](https://github.com/ylechelle/OpenIDFA)

**Comment by alexandracf13** [comment]
Given the approach defined on Feb 19th, this issue is no longer to be considered. Closing.
